
package org.bp.gate.chairs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChairsServiceService", targetNamespace = "http://chairsFactory.bp.org/", wsdlLocation = "http://localhost:8081/soap-api/service/car?wsdl")
public class ChairsServiceService
    extends Service
{

    private final static URL CHAIRSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CHAIRSSERVICESERVICE_EXCEPTION;
    private final static QName CHAIRSSERVICESERVICE_QNAME = new QName("http://chairsFactory.bp.org/", "ChairsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/soap-api/service/car?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHAIRSSERVICESERVICE_WSDL_LOCATION = url;
        CHAIRSSERVICESERVICE_EXCEPTION = e;
    }

    public ChairsServiceService() {
        super(__getWsdlLocation(), CHAIRSSERVICESERVICE_QNAME);
    }

    public ChairsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHAIRSSERVICESERVICE_QNAME, features);
    }

    public ChairsServiceService(URL wsdlLocation) {
        super(wsdlLocation, CHAIRSSERVICESERVICE_QNAME);
    }

    public ChairsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHAIRSSERVICESERVICE_QNAME, features);
    }

    public ChairsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChairsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChairsService
     */
    @WebEndpoint(name = "ChairsServicePort")
    public ChairsService getChairsServicePort() {
        return super.getPort(new QName("http://chairsFactory.bp.org/", "ChairsServicePort"), ChairsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChairsService
     */
    @WebEndpoint(name = "ChairsServicePort")
    public ChairsService getChairsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://chairsFactory.bp.org/", "ChairsServicePort"), ChairsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHAIRSSERVICESERVICE_EXCEPTION!= null) {
            throw CHAIRSSERVICESERVICE_EXCEPTION;
        }
        return CHAIRSSERVICESERVICE_WSDL_LOCATION;
    }

}
